[package]
name = "woodnet-td"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.9.1", features = ["dynamic", "wav"] }
bevy-inspector-egui = "0.17.0"
bevy_mod_picking = "0.11"

